import AvatarMock from '../../../assets/images/avatar.svg'

export const SellersTableHeadMock = [
  'OPERADOR',
  'ID DO PEDIDO',
  'VALOR DO PEDIDO',
  'VALOR DA COBRANÇA',
  'STATUS DO ATENDIMENTO',
  'FORMA DE PAGAMENTO',
  'CRIADO EM',
]
export const SellersTableDataMock = [
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    orderId: 'or_6lEwAjYSnC62wndgL3',
    orderValue: '2654',
    chargeValue: '2654',
    serviceStatus: 'Processando',
    PaymentMethod: 'Debito',
    createdAt: '23/05/23 - 10:03:24',
  },
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    orderId: 'or_6lEwAjYSnC36wndgL3',
    orderValue: '2654',
    chargeValue: '2654',
    serviceStatus: 'Processando',
    PaymentMethod: 'Debito',
    createdAt: '23/05/23 - 10:03:24',
  },
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    orderId: 'or_6lEw4AjYSnC6wndgL3',
    orderValue: '2654',
    chargeValue: '2654',
    serviceStatus: 'Processando',
    PaymentMethod: 'Debito',
    createdAt: '23/05/23 - 10:03:24',
  },
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    orderId: 'or_6lEwAj5YSnC6wndgL3',
    orderValue: '2654',
    chargeValue: '2654',
    serviceStatus: 'Processando',
    PaymentMethod: 'Debito',
    createdAt: '23/05/23 - 10:03:24',
  },
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    orderId: 'or_6l6EwAjYSnC6wndgL3',
    orderValue: '2654',
    chargeValue: '2654',
    serviceStatus: 'Processando',
    PaymentMethod: 'Debito',
    createdAt: '23/05/23 - 10:03:24',
  },
]
