import AvatarMock from '../../../assets/images/avatar.svg'

export const ServicesTableHeadMock = [
  'ATENDIDO POR',
  'ID',
  'CÓDIGO',
  'CLIENTE',
  'VALOR',
  'MARCA',
  'CRIADO EM',
  'STATUS',
]
export const ServicesTableDataMock = [
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    id: 'or_6lEwAjYSnC6wndgL3',
    code: '4002350',
    customer: 'Aline Silva Ramos de Oliveira',
    value: '3000',
    brand: 'Mini',
    createdAt: '23/05/23 - 10:03:24',
    status: 'Processando',
  },
  {
    profilePicture: AvatarMock,
    name: 'Wadie Warren',
    user: '@wadie',
    id: 'or_6lEwAjYSnC5wndgL3',
    code: '4002350',
    customer: 'Aline Silva Ramos de Oliveira',
    value: '3000',
    brand: 'Mini',
    createdAt: '23/05/23 - 10:03:24',
    status: 'Processando',
  },
  {
    profilePicture: AvatarMock,
    name: 'Joe Jordan',
    user: '@joe',
    id: 'or_6lEwAjYSn4CwndgL3',
    code: '4002350',
    customer: 'Aline Silva Ramos de Oliveira',
    value: '3000',
    brand: 'Mini',
    createdAt: '23/05/23 - 10:03:24',
    status: 'Processando',
  },
  {
    profilePicture: AvatarMock,
    name: 'Simmons',
    user: '@simmons',
    id: 'or_6lEwAjYSn3CwndgL3',
    code: '4002350',
    customer: 'Aline Silva Ramos de Oliveira',
    value: '3000',
    brand: 'Mini',
    createdAt: '23/05/23 - 10:03:24',
    status: 'Processando',
  },
  {
    profilePicture: AvatarMock,
    name: 'Simmons',
    user: '@simmons',
    id: 'or_6lEwAjYSnCwndg2L3',
    code: '4002350',
    customer: 'Aline Silva Ramos de Oliveira',
    value: '3000',
    brand: 'Mini',
    createdAt: '23/05/23 - 10:03:24',
    status: 'Processando',
  },
]
