import AvatarMock from '../../../assets/images/avatar.svg'

export const AdministrativeTableHeadMock = [
  'VENDEDORES',
  'Q.ENVIADOS(R$)',
  'Q.ENVIADOS(N)',
  'PAGO(R$)',
  'PAGO(R$)',
  'TME',
  'TMP',
  '%TX CONVERSÃO PAGO(N)',
  '%%TX CONVERSÃO PAGO(R$)',
]
export const AdministrativeTableDataMock = [
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    sendCurrency: '**********',
    sendNumber: '**********',
    paymentCurrency: '**********',
    paymentNumber: '**********',
    tme: '**********',
    tmp: '**********',
    convertionNumber: '**********',
    convertionCurrency: '**********',
  },
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    sendCurrency: '**********',
    sendNumber: '**********',
    paymentCurrency: '**********',
    paymentNumber: '**********',
    tme: '**********',
    tmp: '**********',
    convertionNumber: '**********',
    convertionCurrency: '**********',
  },
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    sendCurrency: '**********',
    sendNumber: '**********',
    paymentCurrency: '**********',
    paymentNumber: '**********',
    tme: '**********',
    tmp: '**********',
    convertionNumber: '**********',
    convertionCurrency: '**********',
  },
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    sendCurrency: '**********',
    sendNumber: '**********',
    paymentCurrency: '**********',
    paymentNumber: '**********',
    tme: '**********',
    tmp: '**********',
    convertionNumber: '**********',
    convertionCurrency: '**********',
  },
  {
    profilePicture: AvatarMock,
    name: 'Ralph Edwards',
    user: '@ralph',
    sendCurrency: '**********',
    sendNumber: '**********',
    paymentCurrency: '**********',
    paymentNumber: '**********',
    tme: '**********',
    tmp: '**********',
    convertionNumber: '**********',
    convertionCurrency: '**********',
  },
]
